[package]
name = "battlesnake-rs"
version = "0.1.0"
authors = ["Corey Alexander <coreyja@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rand = "0.8"
itertools = "0.10.0"
debug_print = "1.0.0"
tracing = "0.1.26"
battlesnake-game-types = { path = "../../battlesnake-game-types" }

[dev-dependencies]
criterion = "0.3"
pprof = { version = "0.5.0", features = [ "criterion", "flamegraph" ] }

[[bench]]
name = "my_benchmark"
harness = false

[lib]
name = "battlesnake_rs"
path = "src/lib.rs"
