version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "battlesnake-web-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ve5s6o5sk8j"
s3_prefix = "battlesnake-web-lambda"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
